version: "3.8"
services:

  terminal-clock:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - geolite2:/usr/share/GeoIP

  geoipupdate:
    image: maxmindinc/geoipupdate
    environment:
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-City
    env_file:
      - account.env
    volumes:
      - geolite2:/usr/share/GeoIP

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

volumes:
    geolite2: